baseurl = "https://www.softwarependula.net"
title = "Software Pendula"
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
enableRobotsTXT = true
enableEmoji = true

googleAnalytics = ""
disqusShortname = "software-pendula"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[taxonomies]
  tag = "tags"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "fruity" # dark themes: monokai, api, fruity, native, rrt, swapoff

[author]
  name = ""

[params.meta]
  keywords = ""
  description = "Personal blog."

[params]
  email = "elroy.parkinson@gmail.com"
  github = "eparkinson"
  twitter = "ElroyParkinson"
  linkedin = "elroy-parkinson-13b61a8"
  theme_colors = "default-dark"
