baseurl = "/"
title = "Software Pendula"
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
enableRobotsTXT = true
enableEmoji = true

googleAnalytics = ""
disqusShortname = "software-pendula"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "fruity" # dark themes: monokai, api, fruity, native, rrt, swapoff

[author]
  name = ""

[params.meta]
  keywords = ""
  description = "Personal blog."

[params]
  email = "myemail"
  github = "github id"
  #gitlab = "gitlab id"
  twitter = "twitter id"
  #linkedin = "linkedin id"
  theme_colors = "default-dark"
