name: AWS Staging Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2
        verbose: false

    - name: Hugo Compile
      run: |
        sudo apt-get install hugo
        hugo --minify --enableGitInfo


    - name: Terraform Deploy to S3
      working-directory: .aws
      run: |
        aws s3 sync ../public/ s3://bz-build-repository/staging/staging.softwarependula.net --delete
        # aws s3 sync ../public/ s3://staging.softwarependula.net/ --delete